### ISSUE TITLE
How can i get `IpcMainEvent`? 

### ISSUE THREAD

**Issue by EthianWong** [vladimiry/electron-rpc-api#17]
![image](https://user-images.githubusercontent.com/12590228/115008953-53282400-9ede-11eb-9b95-1e0aefa70fce.png)

like
![image](https://user-images.githubusercontent.com/12590228/115009077-7521a680-9ede-11eb-86cc-a7a56e257e58.png)

**Comment by vladimiry** [comment]
The `IpcMainEvent` is linked to `this` and it's already [typed](https://github.com/vladimiry/electron-rpc-api/blob/1b6be4d11fa2b7b4dfad9c4214d9e1545a3eda2b/src/lib/ipc-main-api-service.ts#L9).

See example on these lines https://github.com/vladimiry/ElectronMail/blob/50d0888ba9cd9febc19eb83004b0aed77c7221cd/src/electron-main/api/endpoints-builders/general.ts#L180-L188

```typescript
        async hotkey({type}) {
            const methodContext = this;

            if (!methodContext) {
                throw new Error(`Failed to resolve "hotkey" method execution context`);
            }

            const [{sender: webContents}] = methodContext.args;

```
