### ISSUE TITLE
Can we have a chat?

### ISSUE THREAD

**Issue by EpokK** [vladimiry/electron-rpc-api#41]
Hey Vladimir, 
I'm Richard from Proton Mail, we already discussed in the past. I would like to have a chat with you regarding ElectronMail project. Can you send me a message to **richard@proton.me** please?
Thanks.

**Comment by vladimiry** [comment]
A message has been sent from the address specified in https://github.com/vladimiry/ElectronMail/blob/master/package.json#L5.
