### ISSUE TITLE
[question] Does webview communication means `webview <---> main process` or `webview <---> webview`?

### ISSUE THREAD

**Issue by liaodalin19903** [vladimiry/electron-rpc-api#55]
Hi,

First of all, thank you for contributing this repo.
I have 2 questions about it:

1. `createWebViewApiService` creates the api for webview communication,
does it means `webview <---> main process` or `webview <---> webview`?

2. What are the use cases of webview?

3. Is Electron's Webview in the technical category of HTML or in the technical category of Electron? 
If it belongs to Electron, what is its operating principle? Is webview compiled into a Node.js process?

**Comment by vladimiry** [comment]
> does it means webview <---> main process or webview <---> webview?

This lib supports `webview <---> main` communication. But if you need `webview <---> webview` style, one way to do that is via the `main` process used as a mediator/proxy. So `webview <---> main <---> webview` way, where `main` process would simply redirect the requests between the webviews.

> What are the use cases of webview?

Here https://www.electronjs.org/docs/latest/api/webview-tag

> 3) 

Also, here https://www.electronjs.org/docs/latest/api/webview-tag
